### ISSUE TITLE
Split exercises.md and usage-examples.md into separate files named like the different slots in the schedule

### ISSUE THREAD

**Issue by Daniel-Mietchen** [UVA-DSI/git-intro#17]
https://github.com/UVA-DSI/git-intro/blob/master/exercises.md
https://github.com/UVA-DSI/git-intro/blob/master/usage-examples.md
https://github.com/UVA-DSI/git-intro/blob/master/schedule.tsv

**Comment by alonzi** [comment]
exercises split into multiple files
