### ISSUE TITLE
Create demo repo

### ISSUE THREAD

**Issue by Daniel-Mietchen** [UVA-DSI/git-intro#19]
Pete will create a GitHub repository that we will use to demonstrate and test, as per
https://github.com/UVA-DSI/git-intro/issues/14#issuecomment-313563751

**Comment by alonzi** [comment]
complete
https://github.com/alonzi/potatoes

**Comment by Daniel-Mietchen** [comment]
New demo repo: https://github.com/UVA-DSI/potatoes
