### ISSUE TITLE
Create a quick survey of student

### ISSUE THREAD

**Issue by Daniel-Mietchen** [UVA-DSI/git-intro#2]
still to decide: 
- whether we send it out beforehand or do it live on stage

**Comment by alonzi** [comment]
I added some basic questions. Please iterate.

**Comment by Daniel-Mietchen** [comment]
I think what we have now at 
https://github.com/UVA-DSI/git-intro/blob/master/student-pre-survey.tsv
is good to go.

**Comment by alonzi** [comment]
agreed
