### ISSUE TITLE
GitHub accounts for UVa researchers

### ISSUE THREAD

**Issue by dampierch** [UVA-DSI/git-intro#26]
[//]: # "=======================
Instructions for posting issues:
(1) Review what is already there. Perhaps a comment to an existing issue would be more appropriate than opening a new one?  Issues can be a topic idea, a cry for help, a to-do, or a discussion / question about the event itself.
(2) Write your post (below this text blob) using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text.
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview).
(4) Hit the 'Submit new issue' button.
============================"

Good afternoon. I'm a research fellow in the Department of Surgery and Center for Public Health Genomics. I've heard from other researchers at UVa that user accounts and organization accounts can be upgraded to Pro-level so that we can have unlimited private repos and some other perks. Separately, I read on [this GitHub help page](https://help.github.com/en/articles/applying-for-an-educator-or-researcher-discount#about-educator-and-researcher-discounts) about GitHub Education schools. Is UVa a GitHub Education school, or has UVa considered it?

**Comment by Daniel-Mietchen** [comment]
Hi @dampierch . Sorry, saw this only now. As far as I can tell, UVA is not a GitHub Campus Program partner school, and a look at the map at https://education.github.com/schools#apply_for_github_education suggests the same. We had considered it for DSI in 2017 but did not go for it back then &mdash; perhaps worth revisiting. Not sure whether it has been considered by anyone for UVA. I just tried to ping the helpdesk on this (chat ID: uvachat2155) but all operators are marked as busy, so no quick response. Pinging @alonzi as well.

**Comment by Daniel-Mietchen** [comment]
Update from the chat: they could not tell me right away, so they escalated my request. Will report here if/ when anything comes out of that.

**Comment by dampierch** [comment]
Wow thanks for following up that post from a while ago; I had forgotten about it. I applied for Pro-status so that I could have unlimited private repos; easier for cross-lab collaborations. So far, Microsoft has been cool about it. But it still seems worth investigating the Campus Program, especially for DSI. Thanks again
