### ISSUE TITLE
Develop in class exercises

### ISSUE THREAD

**Issue by alonzi** [UVA-DSI/git-intro#4]
example from last year: one potato, two potato

**Comment by alonzi** [comment]
I added what I feel are the core exercises. Please take a look at revise.

**Comment by Daniel-Mietchen** [comment]
I've added a bit more.

**Comment by alonzi** [comment]
links for resources
plan out details for specific exercises (eg potatoes)

**Comment by alonzi** [comment]
put ssh keys in end of part III
put gists in bonus section
